Support configuration of OVS port names in Hyper-V
dbosoft/dotnet-ovn pull request #33
Opened 2024-11-29 11:53 UTC by ChristopherMann

This PR adds the `HyperVOvsPortManager` which can be used get and set the OVS port names in Hyper-V.

2024-11-29 16:39 UTC, ChristopherMann commented on src/OVN.Core/HyperVOvsPortManager.cs
> +public sealed partial class HyperVOvsPortManager(
@fw2568 should we move this to a separate package `Dbosoft.OVN.HyperV` as it is specific to Windows?

2024-12-02 08:27 UTC, fw2568 requested changes

2024-12-02 08:27 UTC, fw2568 commented on src/OVN.Core/HyperVOvsPortManager.cs
> +public sealed partial class HyperVOvsPortManager(
Yes please, however I'm not sure how to add this to [OVNAgent](https://github.com/dbosoft/dotnet-ovn/blob/main/src/OVNAgent/Program.cs) as there has to be some way to add this via command line. Either a standalone tool for windows or something build conditionally (prefered).

2024-12-03 14:30 UTC, ChristopherMann commented on src/OVN.Core/HyperVOvsPortManager.cs
> +public sealed partial class HyperVOvsPortManager(
All code which uses Windows-specific APIs has been moved to the package `Dbosoft.OVN.Windows`.

2024-12-09 13:25 UTC, merged